config/routes.rb
Rails.application.routes.draw do
  resources :messages, only: [:show]
  resources :musics, only: [:index, :show] do
    resources :music_messages
  end
  resources :cars, only: [:index, :show] do
    resources :car_messages
  end
  resources :users, only: [:show]

  root 'welcome#index'

  namespace :recipients_for do
    resources :contents
    resources :recipients, only: [:create]
    resources :all_recipients, only: [:create]
    resources :downloads, only: [:show]
    resources :cars, only: [:new, :create]
    put 'mark_all_as_read', to: 'mark_all_as_read#update'
  end

end

app/models/car.rb
class Car < ActiveRecord::Base
  act_as_messageble

  def message_path(car_id)
    "/cars/#{id}/car_messages/#{car_id}"
  end
end

app/models/music.rb
class Music < ActiveRecord::Base
  act_as_messageble

  def message_path(message_id)
    "/musics/#{id}/music_messages/#{message_id}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :fetch_users

  def fetch_users
    @users = User.all
  end

  def current_user
    if user_id = session[:user_id]
      User.find(user_id)
    else
      User.first
    end
  end
  helper_method :current_user

  def unread_messages_count
    RecipientsFor::ReaderInfo.unread_by_count(
      reciveable_type: current_user.class.name,
      reciveable_id: current_user.id
    )
  end
  helper_method :unread_messages_count
end

app/controllers/car_messages_controller.rb
class CarMessagesController < ApplicationController
  include RecipientsFor::MessageServices
  include RecipientsFor::ReaderServices

  def new
    @car = Car.find(params[:car_id])
    build_message
    set_recipients
  end


  def create
    @car = Car.find(params[:car_id])
    @subject = create_message(
        author: current_user,
        messageable: @car,
        personas: User.all,
        params: subject_params
      )
    if @subject.persisted?
      redirect_to car_car_message_path(@car, @subject)
    else
      set_recipients
      render :new
    end
  end

  #def index
  #end

  def show
    @car = Car.find(params[:car_id])
    show_message(params[:id], current_user)
    reciveables = RecipientsFor::Recipient.reciveables(@car)
    @readers = @car.all_readers(@subject)
  end

  private

  def set_recipients
    find_or_create_receipients(
      messageble: @car,
      personas: User.all,
      notifications: [
        {notification_type: "internal", name: "intern besked", checked: true, internal: true},
        {notification_type: "email", name: "email", checked: false, internal: false},
        {notification_type: "sms", name: "sms", checked: false, internal: false}
      ]
    )
  end



  def subject_params
    params.require(:recipients_for_subject).permit!
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  include RecipientsFor::MessageServices
  include RecipientsFor::ReaderServices

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    #all_messageble_messages(@car)
    @messages = @car.all_messages
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:brand, :model)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def show
    begin
      reader_info = get_reader_info
      return redirect_to_error_page(reader_info[:reason]) unless reader_info[:status] == :ok

      subject = get_subject(reader_info[:value])
      return redirect_to_error_page(reader_info[:reason]) unless subject[:status] == :ok

      link = build_link(subject[:value])
      return redirect_to_error_page(reader_info[:reason]) unless link[:status] == :ok

      return redirect_to link[:value]
    rescue => e
      redirect_to_error_page(e.inspect)
    end
  end

  private

  def get_reader_info
    if reader_info =  RecipientsFor::ReaderInfo.find_by(uuid: params[:id])
      return {status: :ok, value: reader_info}
    end
    return {status: :error, reason: "reader info not found"}
  end

  def get_subject(reader_info)
    if subject = RecipientsFor::Subject.find_by(id: reader_info.subject_id)
      return {status: :ok, value: subject}
    end
    return {status: :error, reason: "subject not found"}
  end

  def build_link(subject)
     case subject.messageable_type
     when "Music"
       link = music_music_message_path(subject.messageable_id, subject.id)
       return {status: :ok, value: link}
     when "Car"
       link = car_car_message_path(subject.messageable_id, subject.id)
       return {status: :ok, value: link}
     end
     return {status: :error, reason: "messageable_ ype not supported"}
  end

  def redirect_to_error_page(error_message)
    flash[:notice] = error_message
    redirect_to root_path
  end
end

app/controllers/music_messages_controller.rb
class MusicMessagesController < ApplicationController
  include RecipientsFor::MessageServices
  include RecipientsFor::ReaderServices

  def new
    @music = Music.find(params[:music_id])
    build_message
    set_recipients
  end


  def create
    @music = Music.find(params[:music_id])
    @subject = create_message(
        author: current_user,
        messageable: @music,
        personas: User.all,
        params: subject_params
      )
    if @subject.persisted?
      redirect_to music_music_message_path(@music, @subject)
    else
      set_recipients
      render :new
    end
  end

  def show
    @music = Music.find(params[:music_id])
    show_message(params[:id], current_user)
    reciveables = RecipientsFor::Recipient.reciveables(@music)
    #build_reader_infos(@subject, reciveables)
    @readers = @music.all_readers(@subject)
  end

  private

  def set_recipients
    find_or_create_receipients(
      messageble: @music,
      personas: User.all,
      notifications: [
        {notification_type: "email", name: "email", checked: true, internal: false},
        {notification_type: "internal", name: "intern besked", checked: false, internal: true}
      ]
    )
  end

  def subject_params
    params.require(:recipients_for_subject).permit!
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: [:show, :edit, :update, :destroy]
  include RecipientsFor::MessageServices
  include RecipientsFor::ReaderServices

  def index
    @musics = Music.all
  end

  def show
    #all_messageble_messages(@music)
    @messages = @music.all_messages
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_music
      @music = Music.find(params[:id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include RecipientsFor::MessageServices

  def show
    @user             = User.find(params[:id])
    @redirect_to      = params[:redirect_to]
    session[:user_id] = @user.id
    @unread_messages = reciveable_messages(
      reciveable_type:  @user.class.name,
      reciveable_id:    @user.id,
      read:             false,
      internal:         true
    )

    @read_messages = reciveable_messages(
      reciveable_type:  @user.class.name,
      reciveable_id:    @user.id,
      read:             true,
      internal:         true
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_messages_helper.rb
module CarMessagesHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/car_messages/_form.html.slim
= simple_form_for  [subject], :url => url_for(action: 'create', controller: controller), :method => 'post' do |f|

  - if subject.errors.any?
    #error_explanation
      h2= "#{pluralize(subject.errors.count, "error")} prohibited this subject from being saved:"
      ul
        - subject.errors.full_messages.each do |msg|
          li= msg

  = f.hidden_field :messageable_type, value: messageble.class.name
  = f.hidden_field :messageable_id, value: messageble.id
  /= f.hidden_field :return_path, value: request_url
  = f.input :title
  /= f.input :attachment, as: :file
  = f.simple_fields_for :contents, content do |c|
    = c.input :body, input_html: { rows: 12 }

  .actions
    = link_to "Cancel", car_path(@car), class: "btn btn-secondary"
    = f.submit 'Save', class: 'btn btn-primary'

app/views/car_messages/_index.slim
table.table.table-bordered
  thead.thead-inverse
    tr
      th Date : Time
      th Subject
      th Author
      th Replies
      th Read
      th
  tbody
    - @messages.each do |message|
      tr
        td = l(message.updated_at, format: :short)
        td = message.title
        td = message.author_name
        td = message.reply_count
        td = message.read_by?(current_user)
        td.text-xs-right
          = link_to "Show", car_car_message_path(@car, message.id), class: "btn btn-secondary"

app/views/car_messages/create.html.erb
<h1>CarMessages#create</h1>
<p>Find me in app/views/car_messages/create.html.erb</p>

app/views/car_messages/new.html.slim
br
.jumbotron
  h3 = @car.brand
  h1 = @car.model
br
== render "form",
  subject: @subject,
  content: @content,
  messageble: @messageble,
  personas: @personas,
  controller: "car_messages"
br
= render "recipients", messageble: @messageble, recipients: @recipients

app/views/car_messages/show.slim
ol.breadcrumb
  li.breadcrumb-item = link_to "Cars", cars_path
  li.breadcrumb-item = link_to [@car.brand, @car.model].join(" "), car_path(@car)


.jumbotron
  h3 = @car.brand
  h1 = @car.model
br
.row
  .col-sm-3
    h4 Recipients
    - if @readers
      table.table.table-bordered
        thead.thead-inverse
          tr
            th Name
            th Read
        tbody
          - @readers.each do |reader|
            tr
              td = reader.name
              td = reader.read ? "Yes" : "No"



  .col-sm-9
    h4 Message
    .card
      .card-block
        h5.card-title = @subject.title
        .card-subtitle.text-muted
          = l(@subject.created_at, format: :short)
          '&nbsp;&nbsp;
          'Author:&nbsp;
          = @subject.author_name
        .card-text = simple_format @subject.body

    h4 Reply
    = render "shared/notice", notice: notice
    = simple_form_for @content do |f|
      == render "shared/error_notifications", model_instance: @content
      .field
        = f.input :body, input_html: { rows: 12 }
        = f.hidden_field :subject_id, value: @subject.id

        = f.hidden_field :return_path, value: session[:request_url] || request.url
        = f.hidden_field :messageble_var_name, value: :car
        = f.hidden_field :render_error_path, value: "/car_messages/show"

        = f.submit 'Reply', class: "btn btn-primary"

    - if @subject.reply_count > 0
      hr
      h4 Replies
      - @subject.replies.each do |reply|
        - unless reply.created_at.nil?
          .card
            .card-block
              .card-subtitle.text-muted
                = l(reply.created_at, format: :short)
                '&nbsp;&nbsp;
                'Author:&nbsp;
                = reply.author_name
              .card-text = simple_format reply.body





- if session[:request_url]
  javascript:
    history.pushState({}, null, "#{session[:request_url]}");
  - session[:request_url] = nil

app/views/cars/index.html.slim
h1 Cars
table.table.table-bordered
  thead.thead-inverse
    tr
      th Brand
      th Model
      th Messages
      th
  tbody
    - @cars.each do |car|
      tr
        td = link_to car.brand, car
        td = car.model
        td = car.all_messages_count
        td
          .text-xs-right
            = link_to 'Show', car , class: "btn btn-secondary"

app/views/cars/show.html.slim
br
.jumbotron
  h3 = @car.brand
  h1 = @car.model



br
h3 All messages
= render "car_messages/index"
br
= link_to 'New Messages', new_car_car_message_path(@car), class: "btn btn-primary"

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-light.bg-faded

  = link_to "recipients_for", root_path, class: "navbar-brand"
  ul.nav.navbar-nav
    li.nav-item
      = link_to "Cars", cars_path, class: "nav-link #{'active' if request.url.include?('car')}"

    li.nav-item
      = link_to "Music", musics_path, class: "nav-link #{'active' if request.url.include?('music')}"
    li.nav-item.dropdown
      a#supportedContentDropdown.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#"  Users
      .dropdown-menu aria-labelledby="supportedContentDropdown"
        - @users.each do |user|
          = link_to user.name, user_path(user, redirect_to: request.url), class: "dropdown-item"
  ul.nav.navbar.nav.float-lg-right
    li.nav-item
    li.nav-item
      = link_to current_user.name, current_user
      - if count = unread_messages_count
        - if count > 0
          '&nbsp;
          .tag.tag-danger
            = count

app/views/layouts/application.html.slim
doctype html
head
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
html
  head
    title RecipientsFor
  body
    .container
      = render 'layouts/navbar'
      = yield

app/views/music_messages/_form.html.slim
= simple_form_for  [subject], :url => url_for(action: 'create', controller: controller), :method => 'post' do |f|

  - if subject.errors.any?
    #error_explanation
      h2= "#{pluralize(subject.errors.count, "error")} prohibited this subject from being saved:"
      ul
        - subject.errors.full_messages.each do |msg|
          li= msg

  = f.hidden_field :messageable_type, value: messageble.class.name
  = f.hidden_field :messageable_id, value: messageble.id
  /= f.hidden_field :return_path, value: request_url
  = f.input :title
  /= f.input :attachment, as: :file
  = f.simple_fields_for :contents, content do |c|
    = c.input :body, input_html: { rows: 12 }

  .actions
    = link_to "Cancel", music_path(@music), class: "btn btn-secondary"
    = f.submit 'Save', class: 'btn btn-primary'

app/views/music_messages/_index.slim
table.table.table-bordered
  thead.thead-inverse
    tr
      th Date : Time
      th Subject
      th Author
      th Replies
      th Read
      th
  tbody
    - @messages.each do |message|
      tr
        td = l(message.updated_at, format: :short)
        td = message.title
        td = message.author_name
        td = message.reply_count
        td = message.read_by?(current_user)
        td.text-xs-right
          = link_to "Show", music_music_message_path(@music, message.id), class: "btn btn-secondary"

app/views/music_messages/_recipients.slim
table.table.table-bordered
  thead.thead-inverse
    tr
      th Recipients
      - @notifications.each do |notification|
        th
          = render "recipients_for/select_all_recipients_check_box",
            messageble: messageble,
            notification_type: notification[:notification_type]
          '&nbsp;
          = notification[:name]
  tbody
    - recipients.each do |recipient|
      tr
        td = recipient.name
        - recipient.notifications.each do |notification|
          td
            = render "recipients_for/recipient_check_box",
              checked: notification[:checked],
              notification_type: notification[:notification_type],
              recipient_id: recipient.id

app/views/music_messages/new.html.slim
br
.jumbotron
  h3 = @music.artist
  h1 = @music.album
br
== render "form",
  subject: @subject,
  content: @content,
  messageble: @messageble,
  personas: @personas,
  controller: "music_messages"
br
= render "recipients", messageble: @messageble, recipients: @recipients

app/views/music_messages/show.slim
ol.breadcrumb
  li.breadcrumb-item = link_to "Music", musics_path
  li.breadcrumb-item = link_to [@music.artist, @music.album].join(" "), music_path(@music)


.jumbotron
  h3 = @music.artist
  h1 = @music.album
br
.row
  .col-sm-3
    h4 Recipients
    - if @readers
      table.table.table-bordered
        thead.thead-inverse
          tr
            th Name
            th Read
        tbody
          - @readers.each do |reader|
            tr
              td = reader.name
              td = reader.read ? "Yes" : "No"



  .col-sm-9
    .card
      .card-block
        h4.card-title = @subject.title
        .card-subtitle.text-muted
          = l(@subject.created_at, format: :short)
          '&nbsp;&nbsp;
          'Author:&nbsp;
          = @subject.author_name
        .card-text = simple_format @subject.title


    - if @subject.reply_count > 0
      h4 Replies
      - @subject.contents[1..-1].each do |content|
        - unless content.created_at.nil?
          .card
            .card-block
              .card-subtitle.text-muted
                = l(content.created_at, format: :short)
                '&nbsp;&nbsp;
                'Author:&nbsp;
                = content.author_name
              .card-text = simple_format content.body

    h4 Reply
    = render "shared/notice", notice: notice

    = simple_form_for @content do |f|
      == render "shared/error_notifications", model_instance: @content
      .field
        = f.input :body, input_html: { rows: 12 }
        = f.hidden_field :subject_id, value: @subject.id

        = f.hidden_field :return_path, value: session[:request_url] || request.url
        = f.hidden_field :messageble_var_name, value: :music
        = f.hidden_field :render_error_path, value: "/music_messages/show"

        = f.submit 'Reply', class: "btn btn-primary"



    - if session[:request_url]
      javascript:
        history.pushState({}, null, "#{session[:request_url]}");
      - session[:request_url] = nil

app/views/musics/index.html.slim
h1 Music
table.table.table-bordered
  thead.thead-inverse
    tr
      th Artist
      th Album
      th Messages
      th
  tbody
    - @musics.each do |music|
      tr
        td = link_to music.artist, music
        td = music.album
        td = music.all_messages_count
        td
          .text-xs-right
            = link_to 'Show', music , class: "btn btn-secondary"

app/views/musics/show.html.slim
br
.jumbotron
  h3 = @music.artist
  h1 = @music.album

br
h3 All messages
= render "music_messages/index"
br
= link_to 'New Messages', new_music_music_message_path(@music), class: "btn btn-primary"

app/views/recipients_for/_recipient_check_box.slim
= check_box_tag("recipient_id_#{recipient_id}",
    recipient_id,
    checked,
    class: "recipient_checkbox #{notification_type}",
    recipient_id: recipient_id,
    notification_type: notification_type,
    authenticity_token: form_authenticity_token)

app/views/recipients_for/_select_all_recipients_check_box.slim
= check_box_tag("select_all_recipients",
    0,
    false,
    class: "select_all_recipients",
    messageble_type: messageble.class.name,
    messageble_id: messageble.id,
    notification_type: notification_type,
    authenticity_token: form_authenticity_token)

app/views/shared/_error_notifications.slim
- if model_instance.errors.any?
  .alert.alert-danger
    h4= "#{pluralize(model_instance.errors.count, "error")} prohibited this subject from being saved:"
    ul
      - model_instance.errors.full_messages.each do |msg|
        li= msg

app/views/shared/_notice.html.slim
- unless notice.blank?
  br
  .alert.alert-success
    = notice

app/views/users/_user_messages.html.slim
table.table.table-bordered
  thead.thead-inverse
    tr
      th Date : Time
      th Subject
      th Author
      th Replies
      th Read
      th
  tbody
    - messages.each do |message|
      tr
        td = l(message.updated_at, format: :short)
        td
          = message.messageable_type
          '&nbsp;:&nbsp;
          = message.title
        td = message.author_name
        td = message.reply_count
        td = message.read_by?(current_user)
        td.text-xs-right
          = link_to "Show", message.messageable.message_path(message.id), class: "btn btn-secondary"

app/views/users/show.html.slim
br
.jumbotron
  h3 You are logged in as
  h1 = @user.name
  br
  = link_to "Back", @redirect_to, class: "btn btn-secondary" if @redirect_to


h3 Unread messages
= render "users/user_messages", messages: @unread_messages

h3 Read messages
= render "users/user_messages", messages: @read_messages

app/views/welcome/index.html.slim
br
.jumbotron
  h1 recipients_for
  'Message and notification system for ruby on rails

h3 How to use this demo
ol
  li Select a user from the 'Users' dropdown above.
  li Notice the user-name in the top right corner.
  li Notice the number of unreadm mesages next to the username
  li Click on Cars / Music in the menu
  li Select a Car or Artist to show messages related to the selection
  li Click on 'New Message' to write a message
  li Write message select recipients and how they should receive the message
  li Save the message
  li Try to select another user from the Users menu and se the list of messages
hr

h3 Overview
hr
.row
  .col-sm-6
    h5 Messages and notification
    ul
      li Write a messages on a subject
      li Select recipients
      li Select deliveriy method
      li Send
      li Recipients are notifyed
      li Recipients can comment


  .col-sm-6
    h5 Fully customizable
    ul
      li Attach messages to any model
      li Recipients can be any model (as long as they have a name)
      li Hooks for external delivery methods e.g. SMS, Email, Slack e.t.c.
      li Service classes for light waight code and minimum memory foodprint
      li Generators for migrations
      li Ajax for update of recipients
      li Write your own views

h3 Details
hr
.row
  .col-sm-6
    h5 From a subject
    ul
      li Se a list of messages
      li Se how many recipients there is
      li Se how many has read the message
      li Se how many replies/ comments there is on a message

  .col-sm-6
    h5 From a user
    ul
      li Se a list of unread messages
      li Se a list of read messages
      li Se a list of all messages
.row
  .col-sm-6
    h5 From a message
    ul
      li Se a list of replies/ comments
      li Se a list of recipients
      li Write a comment
      li When there is a new comment all recipients are notified

  .row
    .col-sm-6
      h5 Source
      ul
        li = link_to 'gem on github', "https://github.com/maxgronlund/recipients_for"
        li = link_to 'Demo project on github', "https://github.com/maxgronlund/RecipientsFor"
        li = link_to 'Live demo', "https://recipients-for.herokuapp.com/"